# Generated by Django 4.2.30 on 2026-08-24 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('CASH_IN', 'Cash In / Deposit'), ('WITHDRAW', 'Withdrawal Payout')], max_length=10)),
                ('payment_method', models.CharField(choices=[('bKash', 'bKash Mobile Banking'), ('Nagad', 'Nagad Mobile Banking'), ('Rocket', 'Rocket Mobile Banking'), ('SSLCommerz', 'SSLCommerz Gateway'), ('Bank', 'Bank Transfer'), ('Card', 'Debit/Credit Card')], default='bKash', max_length=20)),
                ('tran_id', models.CharField(max_length=64, unique=True)),
                ('val_id', models.CharField(blank=True, max_length=64, null=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fee_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount_bdt', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=12)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
